### ISSUE TITLE
Stock Entry

### ISSUE THREAD

**Issue by mohamadsyalvassr** [bumicode/erp#114]
```[tasklist]
### Tasks
- [ ] https://github.com/bumicode/erp/issues/119
- [ ] https://github.com/bumicode/erp/issues/120
- [ ] https://github.com/bumicode/erp/issues/121
- [ ] https://github.com/bumicode/erp/issues/122
- [x] Manual add
```

```[tasklist]
### Relation
```
