### ISSUE TITLE
module/selling

### ISSUE THREAD

**Issue by mohamadsyalvassr** [bumicode/erp#87]
```[tasklist]
### Tasks
- [ ] https://github.com/bumicode/erp/issues/89
- [ ] https://github.com/bumicode/erp/issues/90
- [ ] https://github.com/bumicode/erp/issues/91
- [ ] https://github.com/bumicode/erp/issues/92
- [ ] https://github.com/bumicode/erp/issues/101
- [ ] https://github.com/bumicode/erp/issues/102
- [ ] https://github.com/bumicode/erp/issues/103
- [ ] https://github.com/bumicode/erp/issues/88
- [ ] https://github.com/bumicode/erp/issues/104
- [ ] https://github.com/bumicode/erp/issues/105
- [x] Item Group
- [ ] https://github.com/bumicode/erp/issues/106
- [ ] https://github.com/bumicode/erp/issues/107
- [ ] https://github.com/bumicode/erp/issues/108
- [ ] https://github.com/bumicode/erp/issues/109
- [ ] https://github.com/bumicode/erp/issues/110
```
