### ISSUE TITLE
Sales Order

### ISSUE THREAD

**Issue by mohamadsyalvassr** [bumicode/erp#91]
```[tasklist]
### Tasks \[/admin/selling/sales-orders/create]
- [ ] Ketika 'set warehouse source' dipilih, maka item yang muncul hanya yang terdaftar pada warehouse tersebut
- [ ] Ketika 'item' memiliki lebih dari 1 uom, maka bisa memilih uom mana yang ingin dibeli oleh konsumen
- [ ] https://github.com/bumicode/erp/issues/146
- [ ] Fitur 'scan barcode'
- [ ] Fitur 'pajak / taxes'
- [ ] Fitur 'diskon'
- [ ] Fitur 'account dimensions'
```
